### PR TITLE
add buffer param, to keep a buffer zone around food, spawn point, and…

### PR DESCRIPTION
**Pull request by joram**
… walls.

### CODE REVIEW

**Comment by joram** [comment]
this is still a work in progress, still figuring out how elixir works with docker.

**Comment by Dkendal** [comment]
Hey @joram, the instructions at https://github.com/battle-snake/battle_snake#running-with-docker should be up to date on how to run with docker.

**Comment by joram** [comment]
@Dkendal that's true, but if I'm pulling the image, I'm not running my modified code.
I got it running locally last night, and with a little adjusted the elixir to actually compile (code style might be ugly) but I think it's good for a review now. It's a very simple adjustment to add a buffer, not the fancy voroinoi one.

**Comment by Dkendal** [comment]
FYI you don't have to worry about code style any more with elixir 1.6 because it ships with `mix format` 😄

**Comment by joram** [comment]
Nice, I will mix format, then I think it's good for review.

**Comment by john-swu** [comment]
@Dkendal thoughts?

**Comment by Dkendal** [comment]
Will review tonight!

**Pull request closed without merging**
